# Generated by Django 3.2.5 on 2021-08-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressePostale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.PositiveSmallIntegerField(choices=[(1, 'Simple Adresse'), (2, 'Adresse de Site'), (3, 'Adresse de Domicile'), (4, 'Adresse de livraison énergie (EAN)'), (5, "Adresse définie par l'usager")], default=1)),
                ('desc_autre_usage', models.CharField(blank=True, max_length=256, null=True)),
                ('nom_autre_usage', models.CharField(blank=True, max_length=124, null=True)),
                ('voirie', models.CharField(help_text='En toutes lettres. Les noms de rue ne doivent inclure AUCUNE \t\tautre note ou information, telle que les noms de la sous-commune, etc.', max_length=255, verbose_name='Voirie')),
                ('numero', models.CharField(blank=True, help_text='Si 2 séries de chiffres distincts, utiliser tiret (« - »)', max_length=21, null=True, verbose_name='Numéro')),
                ('boite', models.CharField(blank=True, max_length=7, null=True, verbose_name='boîte')),
                ('localite', models.CharField(blank=True, help_text='La localité, et non pas la commune.', max_length=124, null=True, verbose_name='Localité')),
                ('cp', models.CharField(blank=True, help_text='4 chiffres, pas d’initiale de pays,ni de code ISO', max_length=6, null=True, verbose_name='Code postal')),
                ('region', models.CharField(blank=True, choices=[('BE-VLG', 'Flandre'), ('BE-BRU', 'Bruxelles'), ('BE-WAL', 'Wallonie')], max_length=6, null=True, verbose_name='Région')),
            ],
            options={
                'verbose_name_plural': 'Adresses postales',
            },
        ),
    ]
