# Generated by Django 3.2.5 on 2021-08-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdressePostale',
        ),
    ]
